import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from './ReactQueryProvider'
import { ThemeProvider } from '@/components/theme-provider'

import Header from '@/components/header'
import { AppProvider } from '@/context/app.context'
import Footer from '@/components/footer'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
}

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <ReactQueryProvider>
         <html lang='en' suppressHydrationWarning>
            <body className={inter.className}>
               <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                  <AppProvider>
                     <Header />
                     <main className='container mt-20 mb-5 min-h-screen'>{children}</main>
                     <Footer />
                     <Toaster />
                  </AppProvider>
               </ThemeProvider>
            </body>
         </html>
      </ReactQueryProvider>
   )
}
